### ISSUE TITLE
FE - BE - Simple Communication

### ISSUE THREAD

**Issue by danielwiktorczyk** [danielwiktorczyk/Concordia_Course_Builder#15]
**Context**

As a FE developer, I would like to have a simple communication with the BE API to capture a JSON representation of a Course via the endpoint localhost:8080/api/course/{ID}

**Comment by danielwiktorczyk** [comment]
Moving this ongoing issue to the next sprint

**Comment by MoreWaqar** [comment]
Accomplished and currently available in feature/15, merged in developer/BE  

Key points to use the code:

install node_modules before using code. In the front end folder, use the terminal code "npm install".

To launch front end code, navigate to the folder with the package.json and use the terminal code "npm install".

Two example communications exist. 

A GET request from the front end that pulls a course object from the backend. In the backend, this is done under coursecontroller. In the front end, this is handled by the coursePull method.

A POST request that simulates a login. The user inputs a username and password in the front end and this is validated in the backend and a response is sent back. The backend work is done under the loginController, the front end work is done under the login method in the Main.js. This mold can easily be modified for a full scale login method.
