### ISSUE TITLE
Create A New Domain Model

### ISSUE THREAD

**Issue by danielwiktorczyk** [danielwiktorczyk/Concordia_Course_Builder#21]
As a team member / professor, I would like to have a Domain Model that is:

- created from scratch, 
- added to the Wiki for reference 
- added to the deliverable #1 document.

**Comment by MoreWaqar** [comment]
![domainmodel](https://user-images.githubusercontent.com/35977219/52192301-2ca6d280-2817-11e9-8df7-c60ebfff4507.png)

Draft Domain Model

**Comment by MoreWaqar** [comment]
![image](https://user-images.githubusercontent.com/35977219/52233819-10924800-288e-11e9-95bd-0cf7e6fc9661.png)

Final Diagram for deliverable 1.
