### ISSUE TITLE
Creating a New Account

### ISSUE THREAD

**Issue by danielwiktorczyk** [danielwiktorczyk/Concordia_Course_Builder#28]
A a user who is new to the application, I would like the ability to create a new account and register myself. 

This process should be streamlined, easy, and straightforward.

**Comment by MoreWaqar** [comment]
@danielwiktorczyk This issue is started up in the backend. Please assign the relevant front end people to create a registration page.
Backend currently assumes a user has:

username
password
firstName
lastName
emailAddress
adminRights -- not decided at the front end --
