### ISSUE TITLE
BE - Add objects according to UML structure

### ISSUE THREAD

**Issue by danielwiktorczyk** [danielwiktorczyk/Concordia_Course_Builder#3]
Using the below example for the Domain Model, create the needed classes and hierarchies. Note that this model can be modified and will be adjusted as needed by the team. 
 
![image](https://user-images.githubusercontent.com/24488852/51494927-7cea5300-1d88-11e9-8507-209b8dd2d544.png)

**Comment by danielwiktorczyk** [comment]
We all have to do this anyway in the personal assignment. As such, after today, we will all be on the same page by merging our ideas together

**Comment by MoreWaqar** [comment]
![image](https://user-images.githubusercontent.com/35977219/52233901-4a634e80-288e-11e9-83db-b1a66b28e9ad.png)

Objects added according to Domain Diagram in feature/3.

Can this be closed? @danielwiktorczyk
