### ISSUE TITLE
Engineering writing test passed or not indication

### ISSUE THREAD

**Issue by GwenLegate** [danielwiktorczyk/Concordia_Course_Builder#42]
As a student I would like an indication of whether or not I have passed the EWT so that I can register for ENCS282 without taking ENCS272 first.

**Comment by GwenLegate** [comment]
I'm thinking a boolean added to the user profile should do it but don't want to cause problems with existing code by creating a new attribute that could affect all the existing user code that was just created.  Waqar, I figure you know the backend User related code the best.

**Comment by MoreWaqar** [comment]
EWT Boolean added for now, issue will remain open though as there may be a better solution

**Comment by MoreWaqar** [comment]
Dealt with by simply giving a person who has taken the EWT the ENCS272 prereq
